/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_auth_me_patch"];
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chunks */
        get: operations["list_chunks_documents__document_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Chunks */
        post: operations["search_chunks_search_chunks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Answer a question with cited evidence.
         *
         *     pipeline="agentic" (default): the LangGraph agent picks tools and sources.
         *     pipeline="baseline": fixed retrieve-then-generate over the local index.
         *     Returns 200 for both answered and 'insufficient_evidence' outcomes; check `status`.
         */
        post: operations["ask_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /** Rename Conversation */
        patch: operations["rename_conversation_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message
         * @description Answers with the user's preferred pipeline; follow-ups are rewritten using the
         *     conversation (memory) and answers are scoped to the attached documents.
         */
        post: operations["send_message_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach Document */
        post: operations["attach_document_conversations__conversation_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach Source
         * @description Attach a document from your library or an imported patent (no upload).
         */
        post: operations["attach_source_conversations__conversation_id__sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Detach Document */
        delete: operations["detach_document_conversations__conversation_id__documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Info */
        get: operations["system_info_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patents/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_patents_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patents/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Patents */
        post: operations["search_patents_patents_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patents/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Patent */
        post: operations["import_patent_patents_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Imported */
        get: operations["list_imported_patents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patents/{patent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Patent */
        get: operations["get_patent_patents__patent_id__get"];
        put?: never;
        post?: never;
        /** Delete Patent */
        delete: operations["delete_patent_patents__patent_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare
         * @description Compare 2–4 sources aspect by aspect. The response's `comparison` holds the table;
         *     every cell cites evidence from its own source.
         */
        post: operations["compare_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evaluations */
        get: operations["list_evaluations_evaluations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{experiment}/{run}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation */
        get: operations["get_evaluation_evaluations__experiment___run__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/invention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Analyses */
        get: operations["list_analyses_analysis_invention_get"];
        put?: never;
        /**
         * Analyze Invention
         * @description Takes ~1–3 minutes with local models: features, search, then one check per
         *     feature × document.
         */
        post: operations["analyze_invention_analysis_invention_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/invention/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_analysis_invention__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/invention/{run_id}/report.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Report */
        get: operations["download_report_analysis_invention__run_id__report_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watches */
        get: operations["list_watches_watches_get"];
        put?: never;
        /** Create Watch */
        post: operations["create_watch_watches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watches/{watch_id}/hits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watch Hits */
        get: operations["watch_hits_watches__watch_id__hits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watches/{watch_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Watch
         * @description Search now for publications since the last check (patent API calls: rate-limited).
         */
        post: operations["check_watch_watches__watch_id__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watches/{watch_id}/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Seen */
        post: operations["mark_seen_watches__watch_id__seen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watches/{watch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Watch */
        delete: operations["delete_watch_watches__watch_id__delete"];
        options?: never;
        head?: never;
        /** Set Active */
        patch: operations["set_active_watches__watch_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerSentenceOut */
        AnswerSentenceOut: {
            /** Text */
            text: string;
            /** Citations */
            citations: string[];
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /**
             * Document Ids
             * @description Limit search to these uploaded documents
             */
            document_ids?: string[] | null;
            /**
             * Patent Ids
             * @description Limit search to these imported patents
             */
            patent_ids?: string[] | null;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Top K */
            top_k?: number | null;
            /** Retrieval Mode */
            retrieval_mode?: ("hybrid" | "vector" | "keyword") | null;
            /** Rerank */
            rerank?: boolean | null;
            /**
             * Pipeline
             * @description Default: DEFAULT_PIPELINE setting
             */
            pipeline?: ("agentic" | "baseline") | null;
        };
        /** AskResponse */
        AskResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Query Id
             * Format: uuid
             */
            query_id: string;
            /** Conversation Id */
            conversation_id: string | null;
            /** Question */
            question: string;
            /** Status */
            status: string;
            /** Pipeline */
            pipeline: string;
            /** Answer */
            answer: string | null;
            /** Sentences */
            sentences: components["schemas"]["AnswerSentenceOut"][];
            /** Interpretation */
            interpretation: string | null;
            /** Insufficient Reason */
            insufficient_reason: string | null;
            /** Missing Info */
            missing_info?: string | null;
            /**
             * Comparison
             * @description Structured comparison table (compare tasks only)
             */
            comparison?: {
                [key: string]: unknown;
            } | null;
            /**
             * Grounding Score
             * @description (supported + 0.5 × partially supported) / checked claims
             */
            grounding_score?: number | null;
            /**
             * Verification
             * @description Claim-by-claim verdicts (method, counts, claims)
             */
            verification?: {
                [key: string]: unknown;
            } | null;
            /**
             * Verification Attempts
             * @description Grounding of each attempt when the answer was regenerated
             */
            verification_attempts?: {
                [key: string]: unknown;
            }[];
            /** Error Message */
            error_message: string | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
            summary: components["schemas"]["RunSummaryOut"];
            metrics: components["schemas"]["RunMetricsOut"];
            /** Intent */
            intent?: string | null;
            /**
             * Planner
             * @description rules | llm | llm_fallback_rules
             */
            planner?: string | null;
            /**
             * Legal Question
             * @default false
             */
            legal_question: boolean;
            /** Targets */
            targets?: {
                [key: string]: unknown;
            }[];
            /** Steps */
            steps?: components["schemas"]["StepOut"][];
            /** Recoveries */
            recoveries?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AttachSource */
        AttachSource: {
            /** Document Id */
            document_id?: string | null;
            /** Patent Id */
            patent_id?: string | null;
        };
        /** AuthStatus */
        AuthStatus: {
            /** Authenticated */
            authenticated: boolean;
            /** Auth Required */
            auth_required: boolean;
            user: components["schemas"]["UserOut"] | null;
        };
        /** Body_attach_document_conversations__conversation_id__documents_post */
        Body_attach_document_conversations__conversation_id__documents_post: {
            /**
             * File
             * @description PDF, DOCX or TXT
             */
            file: string;
        };
        /** Body_upload_document_documents_post */
        Body_upload_document_documents_post: {
            /**
             * File
             * @description PDF, DOCX or TXT, up to MAX_UPLOAD_MB
             */
            file: string;
        };
        /** ChatMessageOut */
        ChatMessageOut: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** User Message */
            user_message: string;
            /**
             * Interpreted As
             * @description The standalone question answered, when memory rewrote a follow-up
             */
            interpreted_as: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            response: components["schemas"]["AskResponse"];
        };
        /** ChunkOut */
        ChunkOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Chunk Index */
            chunk_index: number;
            /** Section */
            section: string | null;
            /** Page Number */
            page_number: number | null;
            /** Char Start */
            char_start: number | null;
            /** Char End */
            char_end: number | null;
            /** Token Count */
            token_count: number | null;
            /** Text */
            text: string;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
        };
        /** CompareRequest */
        CompareRequest: {
            /** Sources */
            sources: components["schemas"]["SourceRefIn"][];
            /** Question */
            question?: string | null;
            /**
             * Mode
             * @default auto
             * @enum {string}
             */
            mode: "auto" | "llm" | "extractive";
        };
        /** ConversationCreate */
        ConversationCreate: {
            /** Title */
            title?: string | null;
        };
        /** ConversationDetail */
        ConversationDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Message Count */
            message_count: number;
            /** Documents */
            documents: components["schemas"]["ConversationDocument"][];
            /** Messages */
            messages: components["schemas"]["ChatMessageOut"][];
        };
        /**
         * ConversationDocument
         * @description An attached source: an uploaded document, or an imported patent.
         */
        ConversationDocument: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @default document
             */
            kind: string;
            /** Filename */
            filename: string;
            /** Title */
            title: string | null;
            /** Status */
            status: string;
        };
        /** ConversationRename */
        ConversationRename: {
            /** Title */
            title: string;
        };
        /** ConversationSummary */
        ConversationSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Message Count */
            message_count: number;
            /** Documents */
            documents: components["schemas"]["ConversationDocument"][];
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Title */
            title: string | null;
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Status */
            status: string;
            /** Error Message */
            error_message: string | null;
            /** Page Count */
            page_count: number | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Chunk Count */
            chunk_count: number;
            /** Sections Found */
            sections_found: string[];
            /** Section Detection */
            section_detection: string | null;
            /** Patent Numbers Detected */
            patent_numbers_detected: string[];
        };
        /** EvaluationListItem */
        EvaluationListItem: {
            /** Experiment */
            experiment: string;
            /** Run */
            run: string;
            /** Kind */
            kind: string;
            /** Description */
            description: string;
            /** Finished At */
            finished_at: string | null;
            /** Dataset */
            dataset: string | null;
            /** Synthetic */
            synthetic: boolean;
            /**
             * Draft Labels
             * @default false
             */
            draft_labels: boolean;
            /** N */
            n: number | null;
            /** Variants */
            variants: string[];
        };
        /** EvaluationResult */
        EvaluationResult: {
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /** EvidenceOut */
        EvidenceOut: {
            /**
             * Label
             * @description E1, E2... if this passage was given to the model
             */
            label: string | null;
            /** Cited */
            cited: boolean;
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string | null;
            /** Patent Id */
            patent_id: string | null;
            /** Source Label */
            source_label: string;
            /**
             * Source Type
             * @default upload
             */
            source_type: string;
            /** Source Url */
            source_url?: string | null;
            /** Source Title */
            source_title?: string | null;
            /** Section */
            section: string | null;
            /** Claim Number */
            claim_number: number | null;
            /** Page Number */
            page_number: number | null;
            /** Text */
            text: string;
            /** Rank */
            rank: number;
            /** Method */
            method: string;
            /** Score */
            score: number;
            /** Vector Similarity */
            vector_similarity: number | null;
            /** Keyword Score */
            keyword_score: number | null;
            /** Rerank Score */
            rerank_score: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InventionAnalysisOut */
        InventionAnalysisOut: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Latency Ms */
            latency_ms: number | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
        };
        /** InventionListItem */
        InventionListItem: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Features */
            features: number;
            /** Top Candidate */
            top_candidate: string | null;
        };
        /** InventionRequest */
        InventionRequest: {
            /**
             * Description
             * @description The invention in your own words
             */
            description?: string | null;
            /**
             * Document Id
             * @description Or: an uploaded draft (its abstract and claim 1 are used)
             */
            document_id?: string | null;
            /**
             * Use Patent Search
             * @description Also search configured patent databases (EPO)
             * @default true
             */
            use_patent_search: boolean;
            /**
             * Max Candidates
             * @default 5
             */
            max_candidates: number;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MessageIn */
        MessageIn: {
            /** Message */
            message: string;
        };
        /** PasswordIn */
        PasswordIn: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PatentImportRequest */
        PatentImportRequest: {
            /** Source */
            source: string;
            /** Publication Number */
            publication_number: string;
        };
        /** PatentImportResponse */
        PatentImportResponse: {
            patent: components["schemas"]["PatentOut"];
            /** Already Imported */
            already_imported: boolean;
        };
        /** PatentOut */
        PatentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source */
            source: string;
            /** Publication Number */
            publication_number: string;
            /** Title */
            title: string | null;
            /** Abstract */
            abstract: string | null;
            /** Applicants */
            applicants: string[];
            /** Inventors */
            inventors: string[];
            /** Cpc Codes */
            cpc_codes: string[];
            /** Publication Date */
            publication_date: string | null;
            /** Filing Date */
            filing_date: string | null;
            /** Priority Date */
            priority_date: string | null;
            /** Family Id */
            family_id: string | null;
            /** Url */
            url: string | null;
            /** Has Claims */
            has_claims: boolean;
            /** Has Description */
            has_description: boolean;
            /** Chunk Count */
            chunk_count: number;
            /** Sections Found */
            sections_found: string[];
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
        /** PatentResultOut */
        PatentResultOut: {
            /** Source */
            source: string;
            /** Publication Number */
            publication_number: string;
            /** Title */
            title: string | null;
            /** Abstract */
            abstract: string | null;
            /** Applicants */
            applicants: string[];
            /** Inventors */
            inventors: string[];
            /** Cpc Codes */
            cpc_codes: string[];
            /** Publication Date */
            publication_date: string | null;
            /** Filing Date */
            filing_date: string | null;
            /** Family Id */
            family_id: string | null;
            /** Url */
            url: string | null;
            /** Imported Id */
            imported_id: string | null;
            /**
             * Similarity
             * @description Cosine similarity to the reference invention (not legal)
             */
            similarity?: number | null;
            /** Also Published As */
            also_published_as?: string[];
        };
        /** PatentSearchRequest */
        PatentSearchRequest: {
            /**
             * Keywords
             * @default
             */
            keywords: string;
            /** Cpc */
            cpc?: string[];
            /** Applicant */
            applicant?: string | null;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /**
             * Limit
             * @default 25
             */
            limit: number;
            /**
             * Sources
             * @description Default: all configured
             */
            sources?: string[] | null;
            /**
             * Dedup
             * @description Merge members of the same patent family
             * @default true
             */
            dedup: boolean;
            /**
             * Rank Against Document Id
             * @description Rank results by semantic similarity to this document
             */
            rank_against_document_id?: string | null;
            /** Rank Against Patent Id */
            rank_against_patent_id?: string | null;
        };
        /** PatentSearchResponse */
        PatentSearchResponse: {
            /** Results */
            results: components["schemas"]["PatentResultOut"][];
            /** Sources */
            sources: components["schemas"]["SourceOutcomeOut"][];
            /**
             * Deduplicated
             * @default 0
             */
            deduplicated: number;
            /** Reference Label */
            reference_label?: string | null;
        };
        /** ProfileIn */
        ProfileIn: {
            /** Name */
            name?: string | null;
            /** Preferences */
            preferences?: {
                [key: string]: string;
            } | null;
        };
        /** RegisterIn */
        RegisterIn: {
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
        /** RunListItem */
        RunListItem: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Question */
            question: string;
            /** Status */
            status: string;
            /** Pipeline */
            pipeline: string;
            /** Latency Ms */
            latency_ms: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RunMetricsOut */
        RunMetricsOut: {
            /** Latency Ms */
            latency_ms: number | null;
            /** Timings Ms */
            timings_ms: {
                [key: string]: number;
            };
            /** Prompt Tokens */
            prompt_tokens: number | null;
            /** Completion Tokens */
            completion_tokens: number | null;
            /** Cost Usd */
            cost_usd: number | null;
            /**
             * Citation Coverage
             * @description Share of answer sentences that cite evidence (not yet verified support)
             */
            citation_coverage: number | null;
            /** Invalid Citations */
            invalid_citations: string[];
        };
        /**
         * RunSummaryOut
         * @description The safe, user-facing description of what the system did (no hidden reasoning).
         */
        RunSummaryOut: {
            /** Sources Searched */
            sources_searched: string[];
            /** Passages Retrieved */
            passages_retrieved: number;
            /** Passages Cited */
            passages_cited: number;
            /** Llm Called */
            llm_called: boolean;
        };
        /** SearchHit */
        SearchHit: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Document Id */
            document_id: string | null;
            /** Patent Id */
            patent_id: string | null;
            /** Source Label */
            source_label: string;
            /** Section */
            section: string | null;
            /** Page Number */
            page_number: number | null;
            /** Score */
            score: number;
            /** Method */
            method: string;
            /** Text */
            text: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * Method
             * @default vector
             * @enum {string}
             */
            method: "vector" | "keyword";
            /**
             * Top K
             * @default 5
             */
            top_k: number;
            /** Document Ids */
            document_ids?: string[] | null;
        };
        /** SourceOutcomeOut */
        SourceOutcomeOut: {
            /** Source */
            source: string;
            /** Total */
            total: number;
            /** Returned */
            returned: number;
            /** Query String */
            query_string: string;
            /** Cached */
            cached: boolean;
            /** Latency Ms */
            latency_ms: number;
            /** Error */
            error: string | null;
        };
        /** SourceRefIn */
        SourceRefIn: {
            /** Document Id */
            document_id?: string | null;
            /** Patent Id */
            patent_id?: string | null;
            /** Publication Number */
            publication_number?: string | null;
        };
        /** SourceStatusOut */
        SourceStatusOut: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Status */
            status: string;
            /** Note */
            note: string;
        };
        /**
         * StepOut
         * @description One tool call made by the agent (safe summary, no hidden reasoning).
         */
        StepOut: {
            /** Step Index */
            step_index: number;
            /** Tool Name */
            tool_name: string;
            /** Success */
            success: boolean;
            /** Output Summary */
            output_summary: string | null;
            /** Latency Ms */
            latency_ms: number | null;
        };
        /** UploadResponse */
        UploadResponse: {
            document: components["schemas"]["DocumentOut"];
            /**
             * Duplicate
             * @description True if this exact file was already uploaded
             */
            duplicate: boolean;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Preferences */
            preferences: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchCheckOut */
        WatchCheckOut: {
            /**
             * Watch Id
             * Format: uuid
             */
            watch_id: string;
            /** New Hits */
            new_hits: number;
            /** Imported */
            imported: string[];
            /** Error */
            error: string | null;
        };
        /** WatchCreate */
        WatchCreate: {
            /** Name */
            name: string;
            /**
             * Keywords
             * @default
             */
            keywords: string;
            /** Cpc */
            cpc?: string[];
            /**
             * Reference Document Id
             * @description Rank new publications by similarity to this document
             */
            reference_document_id?: string | null;
            /**
             * Import Top
             * @default 3
             */
            import_top: number;
            /**
             * Lookback Days
             * @description First check looks back this far (days)
             * @default 30
             */
            lookback_days: number;
        };
        /** WatchHitOut */
        WatchHitOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source */
            source: string;
            /** Publication Number */
            publication_number: string;
            /** Title */
            title: string | null;
            /** Abstract */
            abstract: string | null;
            /** Applicants */
            applicants: string[];
            /** Publication Date */
            publication_date: string | null;
            /** Url */
            url: string | null;
            /** Similarity */
            similarity: number | null;
            /** Imported Patent Id */
            imported_patent_id: string | null;
            /** Seen */
            seen: boolean;
            /**
             * Found At
             * Format: date-time
             */
            found_at: string;
        };
        /** WatchOut */
        WatchOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Keywords */
            keywords: string;
            /** Cpc */
            cpc: string[];
            /** Reference Document Id */
            reference_document_id: string | null;
            /** Import Top */
            import_top: number;
            /** Active */
            active: boolean;
            /**
             * Since
             * Format: date
             */
            since: string;
            /** Last Checked At */
            last_checked_at: string | null;
            /** Last Error */
            last_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Hits */
            hits: number;
            /** Unseen */
            unseen: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    update_me_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
        };
    };
    upload_document_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chunks_documents__document_id__chunks_get: {
        parameters: {
            query?: {
                section?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_chunks_search_chunks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                conversation_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"][];
                };
            };
        };
    };
    create_conversation_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_conversation_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_document_conversations__conversation_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_attach_document_conversations__conversation_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_source_conversations__conversation_id__sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachSource"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detach_document_conversations__conversation_id__documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_info_system_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_sources_patents_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatusOut"][];
                };
            };
        };
    };
    search_patents_patents_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatentSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatentSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_patent_patents_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatentImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatentImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_imported_patents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatentOut"][];
                };
            };
        };
    };
    get_patent_patents__patent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_patent_patents__patent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluations_evaluations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationListItem"][];
                };
            };
        };
    };
    get_evaluation_evaluations__experiment___run__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment: string;
                run: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_analyses_analysis_invention_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventionListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_invention_analysis_invention_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventionAnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_analysis_invention__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventionAnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_report_analysis_invention__run_id__report_md_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watches_watches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchOut"][];
                };
            };
        };
    };
    create_watch_watches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watch_hits_watches__watch_id__hits_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchHitOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_watch_watches__watch_id__check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchCheckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_seen_watches__watch_id__seen_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watch_watches__watch_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_active_watches__watch_id__patch: {
        parameters: {
            query: {
                active: boolean;
            };
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
